include $(CPPROOT)/Makefile.first

order_OBJECTS   = order.o
order_LIBRARIES = system data string
APPPROGS += order

portfolio_OBJECTS = portfolio.o
portfolio_LIBRARIES = system data string
APPPROGS += portfolio

datarequest_OBJECTS = datarequest.o
datarequest_LIBRARIES = system data string
APPPROGS += datarequest

include $(CPPROOT)/Makefile.last

