include $(CPPROOT)/Makefile.first

lookup_OBJECTS   = lookup.o
lookup_LIBRARIES = system data string
APPPROGS += lookup

order_OBJECTS   = order.o
order_LIBRARIES = system data string
APPPROGS += order

hmdclient_OBJECTS   = hmdclient.o
hmdclient_LIBRARIES = system data string
APPPROGS += hmdclient

portfolio_OBJECTS = portfolio.o
portfolio_LIBRARIES = system data string
APPPROGS += portfolio

datarequest_OBJECTS = datarequest.o
datarequest_LIBRARIES = system data string
APPPROGS += datarequest

include $(CPPROOT)/Makefile.last

