include $(CPPROOT)/Makefile.first


headermacros_test_OBJECTS	= headermacros_test.o
headermacros_test_LIBRARIES = string
TESTPROGS += headermacros_test

stringtable_test_OBJECTS	= stringtable_test.o
stringtable_test_LIBRARIES = string
TESTPROGS += stringtable_test

integertostring_test_OBJECTS	=	integertostring_test.o
TESTPROGS += integertostring_test

glog_test_OBJECTS	=	glog_test.o
glog_test_LIBRARIES = glog
TESTPROGS += glog_test


include $(CPPROOT)/Makefile.last
