include $(CPPROOT)/Makefile.first


headermacros_test_OBJECTS	= headermacros_test.o
headermacros_test_LIBRARIES = string
TESTPROGS += headermacros_test

stringtable_test_OBJECTS	= stringtable_test.o
stringtable_test_LIBRARIES = string
TESTPROGS += stringtable_test

integertostring_test_OBJECTS	=	integertostring_test.o
TESTPROGS += integertostring_test

log_test_OBJECTS	=	log_test.o
log_test_LIBRARIES = system
TESTPROGS += log_test

include $(CPPROOT)/Makefile.last
