include $(CPPROOT)/Makefile.first

server_OBJECTS = server.o
server_LIBRARIES = system
APPPROGS += server

client_OBJECTS = client.o
client_LIBRARIES = 
APPPROGS += client

include $(CPPROOT)/Makefile.last

